### ISSUE TITLE
Criterion depends on an unmaintained crate

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1044]
We use criterion to run data serialization/deserialization benchmarks. [`cargo audit`](https://rustsec.org/advisories/RUSTSEC-2021-0127) has notified us of the fact that our current version of Criterion depends upon an unmaintained crate [serde_cbor](https://github.com/pyfisch/cbor). [criterion.rs#534](https://github.com/bheisler/criterion.rs/issues/534) is tracking the issue on their side of things. Once that issue is closed, update criterion and remove the `--ignore` added in [aws-sdk-rust#383](https://github.com/awslabs/aws-sdk-rust/pull/383).

**Comment by jdisanti** [comment]
I encountered the TODO comment referencing this issue, and it looks like criterion 0.4 (which should fix this) still hasn't landed.
