### ISSUE TITLE
Server RestXML generates all structure serializers empty in xml_ser

### ISSUE THREAD

**Issue by guymguym** [awslabs/smithy-rs#1101]
I see that in operation_ser.rs the operation code is creating the root xml tag OK:

```rust
pub fn serialize_operation_crate_operation_list_buckets(
    output: &crate::output::ListBucketsOutput,
) -> Result<String, aws_smithy_http::operation::SerializationError> {
    let mut out = String::new();
    {
        let mut writer = aws_smithy_xml::encode::XmlWriter::new(&mut out);
        #[allow(unused_mut)]
        let mut root = writer
            .start_el("ListAllMyBucketsResult")
            .write_ns("http://s3.amazonaws.com/doc/2006-03-01/", None);
        crate::xml_ser::serialize_structure_crate_output_list_buckets_output(output, root)?
    }
    Ok(out)
}
```

But the xml_ser.rs functions are doing nothing - it does have all the functions, but they are all the same and practically empty:

```rust
pub fn serialize_structure_crate_output_list_buckets_output(
    input: &crate::output::ListBucketsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}
```

@david-perez Any idea where things might have changed or perhaps this was so before and I missed it...

**Comment by david-perez** [comment]
@guymguym Thanks for reporting this. There is indeed a bug and it has always been there. This is the relevant code that serializes operation output shapes to XML:

https://github.com/awslabs/smithy-rs/blob/f4d3910f227ceb4962eadac994540edb45137709/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/protocols/serialize/XmlBindingTraitSerializerGenerator.kt#L194-L222

But the call to `operationXmlMembers()`:

https://github.com/awslabs/smithy-rs/blob/f4d3910f227ceb4962eadac994540edb45137709/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/protocols/serialize/XmlBindingTraitSerializerGenerator.kt#L469-L470

is returning the operation's _request_ members, not the response ones.
