### ISSUE TITLE
Users should be able to modify requests at a high level

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1112]
There is a common set of user-reported issues that could be solved by making high-level requests easier to modify.

This change would support these use cases and more:
- Sending unsigned requests to S3.
- Adding custom headers
- Augmenting the user agent sent with requests

Implementers adding a new method to an operation should take care to avoid namespace issues with the new method name(s).

A possible implementation would involve users passing a closer that took a request as input and then returned a request.

Related Issue(s):
- https://github.com/awslabs/aws-sdk-rust/issues/389

**Comment by jdisanti** [comment]
This was completed in #1647.
