### ISSUE TITLE
Generated Server code shouldn't use non-exhaustive tag on struct

### ISSUE THREAD

**Issue by llgerard** [awslabs/smithy-rs#1137]
When using the generated code to write the server side implementation, I would prefer to have the structures defined without the non-exhaustive tag.

This tag makes a lot of sense for client code which needs to be able to work with newer versions of the server code (so new fields are not something the client code has to be aware of).

For server code, I would want updates to the model to mean server code fails to compile until it is updated to match the changes, the most obvious case being for a new output field. 

Notes for myself:
In the generator code, the tag is added as a `RustMetadata` with `additionalAttributes = listOf(NonExhaustive)`.
The tag also forces the use of `.builder()`.

**Comment by llgerard** [comment]
@crisidev seems like you are actively looking at that part of the code, what are your thoughts?

**Comment by david-perez** [comment]
I agree. We're working on improving the ergonomics of using generated model `struct`s in the server implementation in #1095. Since the server works with the latest version of the model, service implementers should be able to construct model structs with and without builders.

**Comment by crisidev** [comment]
@llgerard, I almost have a PR ready to make @required trait behave as expected in the server generation. I agree with you and David, we should remove the non-exaustive tag in server codegen. I will work on it as part of #1095
