### ISSUE TITLE
Server codegen could provide From Trait for operations' error types

### ISSUE THREAD

**Issue by llgerard** [awslabs/smithy-rs#1160]
Each operation gets a dedicated error enum generated making error handling quite verbose with the current lack of `From` trait implementations.

Example when using the following smithy model:
```
@httpError(500) @error("server")
structure InternalServerException { message: String }

operation Op1 {
    input: Input,
    output: Output,
    errors: [
        InternalServerException,
    ],
}
```
The generated code will have in `errors.rs`:
```
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct InternalServerError {
    pub message: std::option::Option<std::string::String>,
}

#[derive(std::fmt::Debug)]
pub enum Op1Error {
    InternalServerError(crate::error::InternalServerError),
}
```

Having the `From<InternalServerError>` trait there would be nice (and should always be possible since the Enum is created from a list of error types in smithy):
```
impl From<InternalServerError> for Op1Error {
  fn from(e : InternalServerError) -> Self { Self::InternalServerError(e) }
}
```

**Comment by crisidev** [comment]
This is something we are already discussing and this issue description sums it up perfectly. I am not 100% sure about the implementation yet, but this is definitely something we will be working on in the short term. Thanks for reporting this.
