### ISSUE TITLE
publisher hydrate-readme fails when running as a git submodule

### ISSUE THREAD

**Issue by guymguym** [awslabs/smithy-rs#1162]
I am building smithy-rs as a git submodule in https://github.com/s3d-rs/s3d and if fails with:

```
     Running `/Users/gu/code/s3d/smithy-rs/tools/target/debug/publisher hydrate-readme --sdk-version 0.6.0 --msrv 1.56.1 --output /Users/gu/code/s3d/smithy-rs/aws/sdk/build/aws-sdk/README.md`
Error: failed to find smithy-rs repository root

> Task :aws:sdk:hydrateReadme FAILED
```

This happens because it checks that .git is a directory, but in a git submodule .git is a regular text file that references the parent project .git location:

```console
$ cat smithy-rs/.git
gitdir: ../.git/modules/smithy-rs
```

This can probably be solved by calling git itself to check it as suggested [here](https://stackoverflow.com/a/957978/2702164) which works as expected also inside a submodule:

```console
$ cd smithy-rs/aws/sdk/build/
$ git rev-parse --show-toplevel
/Users/gu/code/s3d/smithy-rs
```

The error originates from here:
https://github.com/awslabs/smithy-rs/blob/25c50a5f0b6ac6b76bd373ad09bcba4841e4d27c/tools/smithy-rs-tool-common/src/git.rs#L19-L41

BTW - I hacked `is_git_root()` locally to check only exists without is_dir, and that is working as well.

Thanks!

**Comment by guymguym** [comment]
Hi @jdisanti - what do you think ^
Would you prefer a fix where this checks with `git rev-parse --show-toplevel` or maybe just a simplified `is_git_root` that checks only exists without is_dir?
Thanks

**Comment by jdisanti** [comment]
Sorry, I meant to get to this yesterday. Posted a fix: fhttps://github.com/awslabs/smithy-rs/pull/1169

**Comment by guymguym** [comment]
Hi @jdisanti  I used your fix today and it worked well. Many thanks !!

**Comment by guymguym** [comment]
Hi @jdisanti 

Unfortunately I see this is now failing again on main - same reason as before only the code moved to here:

https://github.com/awslabs/smithy-rs/blob/e4e9a1d34f28f7689de159a3b2c115da5137598e/tools/smithy-rs-tool-common/src/git.rs#L154-L156

the problem is that when using smithy-rs as a submodule then `.git` is actually a regular file that contains the relative path to the parent repo and not a dir:
```
$ cat .git    
gitdir: ../.git/modules/smithy-rs
```

what do you think about fixing this as suggested above and just check that .git exists (either file or dir)?
thanks

**Comment by jdisanti** [comment]
@guymguym - Woops, sorry about that. It must have gotten lost in the shuffle with all the release automation refactoring. I posted a PR to fix it: https://github.com/awslabs/smithy-rs/pull/1640
