### ISSUE TITLE
Server enums should not have `Unknown` variants

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1187]
When generating enums for the server, we're generating an `Unknown` variant.

https://github.com/awslabs/smithy-rs/blob/548f6ed4307faae5bb98e431db96ae90a59e489d/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/generators/EnumGenerator.kt#L154-L155

Server enums should not contain this variant. This also means we can no longer `impl From<&str> for MyEnum`, since [`From` is required to never fail](https://doc.rust-lang.org/std/convert/trait.From.html). We should instead implement [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html). This also means deserialization code will be affected, since deserializing a `&str` into an enum can now fail.

**Comment by david-perez** [comment]
> Not having Unknown on the server side would require to do a big refactor similar to https://github.com/awslabs/smithy-rs/issues/1243 ?

@llgerard I don't think so. We should be able to bubble up from the code path that creates the `UnknownVariant`, treat it as an error in deserialization code and reject the request.

**Comment by guymguym** [comment]
@david-perez Should a server be able to hook into this error case of unknown enums? A service might need to specify which error to return in each case. Functionally-wise, a specific error could make the difference between a client receiving a generic "Bad request" error, vs. getting a specific "InvalidXXX" error. 

Just one quick example from the top of my mind is the `InvalidStorageClass` returned by few S3 operations when an invalid storage class enum is provided inside an input structure (both as header and xml).

```
        "com.amazonaws.s3#StorageClass": {
            "type": "string",
            "traits": {
                "smithy.api#enum": [
                    {
                        "value": "STANDARD",
                        "name": "STANDARD"
                    },
                    {
                        "value": "REDUCED_REDUNDANCY",
                        "name": "REDUCED_REDUNDANCY"
                    },
                    ...
                    ...
                ]
            }
        },

```
