### ISSUE TITLE
make it possible to pause the sync script

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#1211]
If the sync script runs while a release is happening, it will add extra commits

**Comment by Velfi** [comment]
It's possible to manually disable/enable workflows from the GitHub actions UI:
![Screen Shot 2022-02-21 at 10 13 09 AM](https://user-images.githubusercontent.com/4008103/154992411-7a2a9193-e5dc-4a31-b6e4-31200789944d.png)

Do we need a more automated solution to this issue?
