### ISSUE TITLE
Run server `httpRequestTest`s and `httpMalformedRequestTests` against actual `Service`s

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1212]
Currently, we're deserializing requests manually in server `httpRequestTest` protocol tests. That is, we build the HTTP request and then call `from_request()` on the operation input wrapper struct corresponding to the operation associated with the test that was passed into `ServerProtocolTestGenerator`. We then assert that what we've deserialized is what we expected in `params`.

Instead, we should be _running the actual service_ defined in the Smithy model of the protocol test. Maybe not run a Hyper server over localhost, but at the very least invoking the `tower::Service` that we get from the `OperationRegistry`. This is a "higher-level" test that has some advantages over how we're currently doing things:
* we test a larger surface area:
    - construction of the `OperationRegistry`, conversion into the `Router` `Service`,
    - the routing logic in `Router` (we could have protocol tests specifically exercising possibly ambiguous routing decisions),
* the test does not need to pull in internal details of the framework like the operation wrapper structs, or the `FromRequest`/`IntoResponse` traits, to which the service implementer does not have access in their code,
* we get to use the `method` field from the test cases; as of now we're ignoring it and sending only `GET` requests, and none of the tests have failed because there's no exercised code path that looks at the HTTP method (if our `Router` had been in the code path, it would have caught a possible failure),

Overall we get more assurances.

Note though that the actual assertions against `params`s would be made _inside the operation handlers_ that we'd code-generate (perhaps as closures). It's unclear what we should return from the operation handlers though, unless the output operation struct is `Default`.

For `httpMalformedRequestTest`s, the assertions are against HTTP responses, so they'd continue to go in the test functions.

Note that this approach is also how `awslabs/smithy-typescript` operates.

**Comment by david-perez** [comment]
We're just missing running the `httpMalformedRequestTests` against actual services using the same approach we've taken for the `httpRequestTest`s.

**Comment by jjant** [comment]
Completed in #1904.
