### ISSUE TITLE
Allow users to set HTTP Connectors in Configs

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1225]
Refactor our current network stack to allow users to set HTTP `Connector`s in Service Configs and Shared Configs.

Then, update Service Client creation to use this connector instead of creating a connector from defaults based on the currently enabled features.

This is in support of the ["How we should use features" RFC](https://github.com/awslabs/smithy-rs/pull/1067).

**Comment by jdisanti** [comment]
The connector customization needs to play into network calling credential providers (e.g., IMDS, HTTP token, etc) provider initialization as well: https://github.com/awslabs/aws-sdk-rust/issues/579

**Comment by jdisanti** [comment]
This would probably be implemented along side https://github.com/awslabs/smithy-rs/issues/960

**Comment by Velfi** [comment]
This is partly implemented by #1918

**Comment by jdisanti** [comment]
This was included in [release-2022-12-14](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2022-12-14).
