### ISSUE TITLE
Blank env credentials should be treated as missing

### ISSUE THREAD

**Issue by elrob** [awslabs/smithy-rs#1271]
Description, motivation etc in https://github.com/awslabs/smithy-rs/pull/1272

**Comment by elrob** [comment]
Closed with:
https://github.com/awslabs/smithy-rs/pull/1272

And release: https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.10.1

**Comment by Velfi** [comment]
released in v0.10.1
