### ISSUE TITLE
[EC2 customization] Custom retry delays for 

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#132]
ModifyNetworkInterfaceAttribute and AssignPrivateIpAddresses both require custom retry configuration: https://github.com/aws/aws-sdk-go/commit/a25e309b0bf343415200bab81ed37ced051bc70a

**Comment by jdisanti** [comment]
The Go V2 SDK does not implement this customization, and it has been superceded by the newer standard retry spec. We don't need to do this work.
