### ISSUE TITLE
[Machine learning customization] Endpoint customization

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#139]
For Operation Predict, replace request endpoint with value from PredictEndpoint input member.

**Comment by jdisanti** [comment]
This might be solved by endpoints 2.0. Adding the `retriage` tag to confirm later.

**Comment by rcoh** [comment]
This will be solved by EP2 if it isn't already

**Comment by aajtodd** [comment]
As of 6/5/2024 the machine learning model does not include endpoint rules for this yet.
