### ISSUE TITLE
Model simple.smithy should emit a DANGER event

### ISSUE THREAD

**Issue by crisidev** [awslabs/smithy-rs#1489]
The model [simple.smithy](https://github.com/awslabs/smithy-rs/blob/main/codegen-server-test/model/simple.smithy) should emit a DANGER event like

```
DANGER: com.amazonaws.simple#StoreServiceBlob (HttpMethodSemantics)
     @ codegen-server-test/python/model/simple.smithy
     |
 111 | @http(method: "GET", uri: "/service/{id}/blob")
     |       ^
     = This operation uses the `GET` method in the `http` trait, but the `content` member is sent as the payload of the request because it is marked with the `httpPayload` trait. Many HTTP clients do not support payloads with GET requests. Consider binding this member to other parts of the HTTP request such as a query string parameter using the `httpQuery` trait, a header using the `httpHeader` trait, or a path segment using the `httpLabel` trait.
```

caused by [this line](https://github.com/awslabs/smithy-rs/blob/main/codegen-server-test/model/simple.smithy#L111).

The DANGER event is not emitted and we don't even get a warning.

I have found a very weird way to make smithy emit the DANGER event:

The [python subfolder](https://github.com/awslabs/smithy-rs/tree/main/codegen-server-test/python) of `codegen-server-test` contains a folder called `model` which is a symlink to the `model` folder of its parent `codegen-server-test`. Changing this symlink into a real folder and linking the models inside it triggers the DANGER event when running `./gradlew codegen-server-test:python:assemble`.

I think you can imagine my surprise when this happened.

I am not sure if this is an issue with smithy-rs or smithy itself or a combination of the two.

Repro: 

- Clone https://github.com/awslabs/smithy-rs/tree/crisidev/danger-no-symlinks
- Run `./gradlew codegen-server-test:python:assemble`

**Comment by rcoh** [comment]
I think this comes from smithy and not from smithy-rs

**Comment by 82marbag** [comment]
@jdisanti might have stumbled on this too

**Comment by jdisanti** [comment]
When I run the `codegen-test:check` target, I see evidence that validation of the classpath imported models is actually occurring:
```
WARNING: - (ModelDeprecation)
     @ /Users/jdisanti/src/smithy-rs/codegen-test/model/misc.smithy
     |
   1 | $version: "1.0"
     |           ^
     = Smithy IDL 1.0 is deprecated. Please upgrade to 2.0.
```
However, no `DANGER` messages appear even though they should definitely be present in this `misc.smithy` at `main@e3239e1a17ea0165849ce5379ae0fe40bdb16577`.

I think this may be a Smithy bug.

**Comment by jdisanti** [comment]
Filed https://github.com/awslabs/smithy/issues/1387 on Smithy.

**Comment by crisidev** [comment]
Fixed by: https://github.com/awslabs/smithy/pull/1525
