### ISSUE TITLE
Try out `prettyplease` instead of `rustfmt`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1526]
We run `cargo fmt` (which uses `rustfmt`) on the generated artifacts to prettify the code. This is useful for humans inspecting the generated output.

However, `rustfmt` often bails when attempting to format many parts of contrived generated code.

Consider using [`prettyplease`](https://docs.rs/prettyplease/latest/prettyplease/), which is faster and is a good fit for generated code.

https://github.com/awslabs/smithy-rs/blob/46984ab91d027e6a4d1e312c125a850f5cb23cfd/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/testutil/Rust.kt#L227-L227
https://github.com/awslabs/smithy-rs/blob/46984ab91d027e6a4d1e312c125a850f5cb23cfd/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/ServerCodegenVisitor.kt#L147-L147
https://github.com/awslabs/smithy-rs/blob/46984ab91d027e6a4d1e312c125a850f5cb23cfd/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/CodegenVisitor.kt#L134-L134
https://github.com/awslabs/smithy-rs/blob/46984ab91d027e6a4d1e312c125a850f5cb23cfd/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/CoreRustSettings.kt#L38-L38

**Comment by jdisanti** [comment]
Prettyplease doesn't preserve comments and [the maintainer doesn't want to support that](https://github.com/dtolnay/prettyplease/issues/50), so it's not a viable option for smithy-rs.
