### ISSUE TITLE
Support for merging server routers

### ISSUE THREAD

**Issue by kiiadi** [awslabs/smithy-rs#1547]
I have a use-case where I have two smithy services that I want to be satisfied by a single server implementation on a single address binding. Currently there is no way to bind multiple `Router` implementations to the same `hyper` address binding.

Something like this would be great:

```rs
let app: Router = service_a::OperationRegistryBuilder()...

let serviceB: Router = service_b::OperationRegistryBuilder()...

app.merge(serviceB);
```

**Comment by crisidev** [comment]
We could do something similar to what Axum is doing here: https://github.com/tokio-rs/axum/blob/main/axum/src/routing/mod.rs#L257

Doc about Axum router merging: https://github.com/tokio-rs/axum/blob/main/axum/src/docs/routing/merge.md

**Comment by david-perez** [comment]
Closing in favor of https://github.com/awslabs/smithy-rs/issues/2979.
