### ISSUE TITLE
Python: Integration test for pokemon service fails on MacOS

### ISSUE THREAD

**Issue by drganjoo** [awslabs/smithy-rs#1552]
`make test` fails with an error `TypeError: cannot pickle 'builtins.PyApp' object`

**Preliminary Analysis**: Shared socket implementation on MacOS differs from Linux. A custom pickle serialize / deserialize routine might need to be written to pass shared fd across python processes.

**Failing Test**: tests/simple_integration_test.rs

**SDK Version Tested**: v0.45.0

**How to reproduce**:

`cd rust-runtime/aws-smithy-http-server-python/examples`     
`make test`

**Comment by crisidev** [comment]
Fixed by #1609
