### ISSUE TITLE
Python: pokemon service example should link with .dylib instead of .so on MacOS

### ISSUE THREAD

**Issue by drganjoo** [awslabs/smithy-rs#1553]
When pokemon service example is run on Mac it displays an error:

```
from libpokemon_service_sdk.error import \  
ModuleNotFoundError: No module named 'libpokemon_service_sdk'
thread panicked while panicking. aborting.
```

**Initial Analysis**: This is happening because on MacOS, libpokemon_service_sdk has the extension .dylib not .so. Makefile is creating a soft link to the generated sdk using the incorrect extension.

**Target OS**: MacOs

**Affected**: Python pokemon service example

**Server Version**: v0.45.0

**How to reproduce**:

```
rust-runtime/aws-smithy-http-server-python/examples
make test
```

**Comment by crisidev** [comment]
Fixed by #1609.
