### ISSUE TITLE
Errors Tracking

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1582]
This issue tracks the improvements we want to make to errors in smithy-rs and the SDKs during Q3

- [ ] [Error types should not implement source _and_ print inner error in Display](https://github.com/awslabs/smithy-rs/issues/1345)
- [ ] [Better error context](https://github.com/awslabs/smithy-rs/issues/1568)

**Comment by jdisanti** [comment]
Closing this tracking issue in favor of #1692.
