### ISSUE TITLE
Create a "native" smithy client to investigate how we should refactor our current implementation

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1653]
Spend at most two weeks investigating:
- What if smithy client was a function instead of a struct?
- Can generics be removed from the smithy client without incurring a performance hit?
- Could a native smithy client be refactored to actually use the `retry_config`, `sleep_impl`, and `timeout_config` set on the service config?
- What changes that we can make are "one-way doors" and which are "two-way doors"?

The output of this task will likely be an RFC

**Comment by jdisanti** [comment]
> What if smithy client was a function instead of a struct?

Merely converting the `aws_smithy_client::Client` into a function is not great. It ends up having 6 generic types with 6 arguments to abstract away a whole 10 lines of code.

I think the better alternative here is to completely eliminate `aws_smithy_client::Client` by moving `call` and `call_raw` into the fluent client, and creating a builder for the fluent client.

The timeout/retry creation could potentially be centralized within aws-smithy-client by having a function that operates on the tower `ServiceBuilder`.

**Comment by rcoh** [comment]
seems reasonable to me!

**Comment by jdisanti** [comment]
This is no longer relevant since the Smithy client will no longer exist once the middleware implementation is removed.
