### ISSUE TITLE
Mutex Lock held across and `.await` point in `aws-smithy-http-server-python`

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1674]
Clippy helpfully pointed out that this code is incorrect:
```rust
async fn yield_data_chunk(
    body: Arc<Mutex<aws_smithy_http::byte_stream::ByteStream>>,
) -> PyResult<Bytes> {
    let mut stream = body.lock();
    match stream.next().await {
        Some(bytes) => bytes.map_err(|e| PyRuntimeError::new_err(e.to_string())),
        None => Err(PyStopIteration::new_err("stream exausted")),
    }
}
```

Please fix it at your earliest convenience and then remove the `#[allow]` we added to ignore it.

**Comment by crisidev** [comment]
This was me trying to be smart and promote some come re use.. we will fix it. This is not used by anyone right now, so it is not a priority! Thanks for reporting this.
