### ISSUE TITLE
When `runtimeConfig` is _not_ specified, the default behavior is still not using the latest runtime crate versions on crates.io

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1676]
After #1635, we made it so that if the `runtimeConfig` key is specified, you now don't need to specify `version: "DEFAULT"` to make the code generated crate depend on the runtime crates on crates.io. Instead, now users have more flexibility: by default it will use the latest crates on crates.io, but they can also use the `versions` (note the plural) key to specify an explicit version for a runtime crate, or a path dependency.

However, if the `runtimeConfig` key is _not_ specified, then we go through the else branch here

https://github.com/awslabs/smithy-rs/blob/30d985ad9d39849bb40705d244413eae2764ba7f/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/RuntimeTypes.kt#L92-L78

and `RuntimeCrateLocation` is thus set to `RuntimeCrateLocation.Path("../")`, a path dependency. So the default behavior is still not using the latest runtime crate versions on crates.io in this case.

**Comment by 82marbag** [comment]
Can this be closed?

**Comment by david-perez** [comment]
Yes. Closing.
