### ISSUE TITLE
Feature request: `From` and `Into` for datetime

### ISSUE THREAD

**Issue by allan2** [awslabs/smithy-rs#1690]
It would be nice if `aws_smithy_types::date_time::DateTime` had `From`/`Into` for crates like `chrono` and `time`.

(I'm assuming these conversions are safe. I saw that `SystemTime` uses `try_from` and `to_chrono_utc()` just works, but I did not look into it further)

**Comment by jdisanti** [comment]
These conversions are already provided by the [`aws-smithy-types-convert`](https://crates.io/crates/aws-smithy-types-convert) crate.
