### ISSUE TITLE
Run `cargo clippy` when building the Pokémon Service

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1727]
We're only running `cargo test` in CI:

https://github.com/awslabs/smithy-rs/blob/fd94858db80d4ea03cbff47f223171172e85faae/tools/ci-build/scripts/check-server-e2e-test#L10

https://github.com/awslabs/smithy-rs/blob/fd94858db80d4ea03cbff47f223171172e85faae/tools/ci-build/scripts/check-server-python-e2e-test#L9

**Comment by GeneralSwiss** [comment]
Are you wanting the rust-runtime Makefiles to be edited to include `clippy` as a target? Or would you rather have the `cargo clippy` command injected in the respective `ci-action/scripts`? Do you want to use `--fix`? I you want the action scripts to be edited, I noticed the Python one copyies some dynamic libraries around during build -- does this need to happen for `cargo clippy` to work correctly? (For the Python script there is just a call to `make test` and no reference to be able to use `clippy` outside of the Makefile definition, so I wasn't sure.

**Comment by david-perez** [comment]
I guess we should create a `test` target in [aws-smithy-http-server/examples/Makefile](https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/rust-runtime/aws-smithy-http-server/examples/Makefile) just as we have in [aws-smithy-http-server-python/examples/Makefile](https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/rust-runtime/aws-smithy-http-server-python/examples/Makefile#L38), and then both CI scripts ([1](https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/tools/ci-build/scripts/check-server-e2e-test), [2](https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/tools/ci-build/scripts/check-server-python-e2e-test)) invoke `make test`, for consistency.

> Are you wanting the rust-runtime Makefiles to be edited to include clippy as a target? 

Yes. The CI scripts then just invoke `make clippy`.

> Do you want to use --fix?

No.

> If you want the action scripts to be edited, I noticed the Python one copies some dynamic libraries around during build -- does this need to happen for cargo clippy to work correctly?

Should not be required, no.

**Comment by GeneralSwiss** [comment]
Just out of curiosity, what's the benefit here? Is this to just convey "we use clippy and you should too, see how it can be included in this sample project"?

**Comment by david-perez** [comment]
Yeah, mostly. We want to provide a good example service and running clippy in CI is a good practice to follow idioms and such.

**Comment by david-perez** [comment]
Closed by https://github.com/awslabs/smithy-rs/pull/1742.
