### ISSUE TITLE
`std::fmt::Debug` implementation on `enum`s does not honor the `sensitive` trait

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#1745]
This model:

```smithy
@sensitive
@enum([
    { value: "en" },
    { value: "es" },
])
string Enum
```

generates:

```rust
#[allow(missing_docs)] // documentation missing in model
#[derive(
    std::clone::Clone,
    std::cmp::Eq,
    std::cmp::Ord,
    std::cmp::PartialEq,
    std::cmp::PartialOrd,
    std::fmt::Debug,
    std::hash::Hash,
)]
pub struct Enum(String);
impl Enum {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        &self.0
    }
    /// Returns all the `&str` representations of the enum members.
    pub fn values() -> &'static [&'static str] {
        &["en", "es"]
    }
}
impl<T> std::convert::From<T> for Enum
where
    T: std::convert::AsRef<str>,
{
    fn from(s: T) -> Self {
        Enum(s.as_ref().to_owned())
    }
}
```

Note how we `derive(Debug)`, so the [`sensitive`](https://awslabs.github.io/smithy/2.0/spec/documentation-traits.html#sensitive-trait) trait is not being honored.

We derive `Debug` because of the `SymbolMetadataProvider`:

https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/SymbolMetadataProvider.kt#L134-L134

which gets rendered here in the case of enums:

https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/EnumGenerator.kt#L128-L128

---

As an aside, it's not clear to me whether we want `Debug` to honor `sensitive`. The spec for `sensitive` reads:

> Sensitive data MUST NOT be exposed in things like exception messages or log output. Application of this trait SHOULD NOT affect wire logging (i.e., logging of all data transmitted to and from servers or clients).

Although the `Display` implementation is used by default in the logging frameworks I know of, `Debug` can be used in `DEBUG`-level logging e.g. via `{#?}`, so to be on the safe side I would advocate for making `Debug` honor it. However, [according to the standard library](https://doc.rust-lang.org/std/fmt/trait.Debug.html), `Debug` is meant for programmer-facing output in a _debugging_ context: there's an argument to be made that if the Smithy spec calls out that `sensitive` should not affect wire logging (which should generally only be used in a debugging context), then `Debug` should not honor `sensitive`.

In any case, whatever we decide, we're currently being inconsistent, because our implementation of `Debug` for `structure` shapes _does_ honor `sensitive`:

https://github.com/awslabs/smithy-rs/blob/ffafbec885c1e83a460fed38fc98119bb63d0439/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/StructureGenerator.kt#L108-L127

**Comment by jdisanti** [comment]
Why would an enum ever be sensitive? Its values are in plain sight in the model.
