### ISSUE TITLE
Add getters to every value in client `Config`

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1747]
The client `Config` should have getters for every value that it holds.

**Comment by DavidSouther** [comment]
There are a couple places that, for debugging purposes, I wanted to include `region` in a log message. Having direct access to that via `client.conf()` would be a Nice to Have.

**Comment by kastolars** [comment]
Has anyone taken on this issue? If not I'm down!

**Comment by jdisanti** [comment]
@kastolars - You're welcome to work on this!

The `Config` struct is created by the [`ServiceConfigGenerator`](https://github.com/awslabs/smithy-rs/blob/e171ce0274dabae71781e014aa84f0efdd1fab21/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/ServiceConfigGenerator.kt#L111), but most of its members are added via decorators/customizations. This is due to the flexible nature of the code generator.

So what you want to look for are pieces of code that match on `ServiceConfig.ConfigStruct`, like [this line in `RegionProviderConfig`](https://github.com/awslabs/smithy-rs/blob/1a0f81ae33816c10c9d305f33ea03da23c6265ef/aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/RegionDecorator.kt#L109). This particular example is adding a `region` field to `Config`, but the other parts of that `when` statement aren't adding an equivalent getter for it (you'll see they _are_ adding a method to the builder for it though). The [`AppNameCustomization`](https://github.com/awslabs/smithy-rs/blob/e171ce0274dabae71781e014aa84f0efdd1fab21/aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/UserAgentDecorator.kt#L149) has an example of both the field and the getter being added correctly.

Let me know if you have questions! 😄

**Comment by kastolars** [comment]
Okay I think everything is clear, taking a crack at it 👍🏻

**Comment by kastolars** [comment]
Should [this](https://github.com/awslabs/smithy-rs/blob/1a0f81ae33816c10c9d305f33ea03da23c6265ef/aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/RegionDecorator.kt#L109) and all other getters pre wrapped by `writable` ? I noticed it in the `AppNameCustomization` example you provided.

**Comment by kastolars** [comment]
Okay also I've noticed in the `AppNameCustomization` example, the getter returns a reference. Is it safe to assume that all getters will be using `as_ref`, or perhaps some may use `&`?

**Comment by jdisanti** [comment]
I think `as_ref` is only necessary where the type changes as well. For example, `&String` -> `&str`.

**Comment by kastolars** [comment]
Having some issues with pre-commit checks on Windows, might need to switch to my other machine. I'll open a PR once I get around it.

**Comment by jdisanti** [comment]
I don't know. I haven't seen that before. If you want to work around this, you can comment out the Ktlint part of the `.pre-commit-config.yaml`, or commit with `--no-verify` to skip pre-commit entirely. There are `ktlint` and `ktlintFormat` Gradle targets that can be run manually, and these will download Ktlint through Gradle rather than through pre-commit. In the worst case, our continuous integration will run it and tell you what needs to be fixed in the log output once a PR is created.

**Comment by kastolars** [comment]
For the [IdempotencyTokenProviderCustomization](https://github.com/awslabs/smithy-rs/blob/main/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/config/IdempotencyTokenProviderCustomization.kt#L23), I noticed there's [no implementation or derivation](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/inlineable/src/idempotency_token.rs#L40) of `AsRef` or `Borrow` or `Clone/Copy` traits. Should I implement one of those traits or perhaps is there a better way to approach this?

**Comment by jdisanti** [comment]
I think it should be fine to implement `Clone` for `IdempotencyTokenProvider`, but it should be a manual implementation that matches on `Inner`, and for the `Random` variant, returns `IdempotencyTokenProvider::random()` instead of cloning the `fastrand::Rng`. The use-case I'm thinking of here is that someone wants to use the same idempotency token provider in another client, and having it generate the exact same tokens is probably undesirable.

**Comment by jdisanti** [comment]
This was implemented in #1761. Thank you, @kastolars!
