### ISSUE TITLE
[Python] Support event streaming trait

### ISSUE THREAD

**Issue by crisidev** [awslabs/smithy-rs#1752]
Support Smithy [event streaming](https://awslabs.github.io/smithy/2.0/spec/streaming.html?highlight=streaming#event-streams) trait.

**Comment by XiangyangShi** [comment]
Plus one on this.
Yes please!

**Comment by crisidev** [comment]
Now that union support have been merged (https://github.com/awslabs/smithy-rs/pull/2427) we are confident we can deliver event streaming support. I don't have a timeline, but should happen soon.
