### ISSUE TITLE
Smithy rust doesn't supported arbitrary precision numbers in Document type

### ISSUE THREAD

**Issue by DanielBauman88** [awslabs/smithy-rs#1769]
Smithy rust does not support arbitrary precision numbers in the Document type.
Would adding this functionality be something that the smithy team would support (for rust and other languages)?
I'm asking about supporting this in principle, not asking for a commitment to deliver this, rather if you would be open to PRs to support this functionality.

Quoting from the smithy idl 2.0 - https://awslabs.github.io/smithy/2.0/spec/simple-types.html#document
`
a JSON-like data model and can contain UTF-8 strings, arbitrary precision numbers, booleans...
`

The Document type contains type [Number](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-types/src/lib.rs#L71) which only supports u64, i64 or f64 values. The comments indicate that the implementation was modelled on serde but support for [arbitrary precision](https://github.com/serde-rs/json/blob/165f3abb787bfb3c64be8dda99d5a0d6229eb9b1/Cargo.toml#L41-L44) was not implemented.

**Comment by jdisanti** [comment]
I think implementing #312 would add this since we would need to add additional arbitrary precision variants to the existing `Number` type.

**Comment by DanielBauman88** [comment]
Yeah that would resolve this too - as long as changes to serialization/deserialization were piped in to use those options when deserializing/serializing numbers.
eg: https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-json/src/deserialize.rs#L325

Would this be something that would get support in other languages too? Should I create this issue in each smithy repo or can this be tracked here?

**Comment by jdisanti** [comment]
> Is there anywhere to create issues for smithy implementations in general?

I don't think there is anything like this today. The most central location would be https://github.com/awslabs/smithy, but that really tracks the Java implementation for parsing IDL and the core logic for building Smithy code generators.

**Comment by goabv** [comment]
Based on the communication thread closing this issue (to avoid duplication) as this is connected to https://github.com/awslabs/smithy-rs/issues/312
