### ISSUE TITLE
Reconsider internal module / structure

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#177]
Currently it feels like there are one too many layers:

```
ListTablesOperation, ListTablesOperationInput, ListTablesOperationInputBuilder
```
After we've implemented a couple of more services and customizations, we should explore of `ListTablesOperationInput` or `ListTablesOperation` can be removed. (Or other potential simplifications.)

Notes:
- Currently ListTablesOperation does double duty and drives the request parsing. It currently holds the `Input` as its only field but in the future would hold configuration params like `validate_crc32_checksum: bool`
- ListTablesOperationInputBuilder exists because `ListTablesOperationInput` construction can be fallible, but since there is _already_ an extra layer, maybe that fallibility is used during `ListTablesOperation` construction?

**Comment by Velfi** [comment]
We should consider making operations private as a first step. Also, the requirement for extra fields is likely no longer relevant.

**Comment by jdisanti** [comment]
I think this is all done.
