### ISSUE TITLE
Verify streaming payload sizes

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1801]
When a response has a streaming body with a `Content-Length` header, the SDK needs to verify that the full payload is received, or produce an error if not. For example, S3 GetObject can close the connection unexpectedly before all the bytes are received.

This might already be working correctly, but needs to be verified. Add an integration test.

**Comment by Velfi** [comment]
I confirmed with @seanmonstar that `hyper` will error if the connection is closed before the body `EOF` is read. I believe that the exact check happens in [this code](https://github.com/hyperium/hyper/blob/91e83b7e486da956439df4439b32ad9e9977cbb2/src/proto/h1/dispatch.rs#L209) for HTTP 1.1 connections. While I do agree that it's good to test your assumptions, I think we should rely on `hyper` testing itself to protect us from this.

**Comment by seanmonstar** [comment]
That code you linked is rather checking if the user still cares about the body, and if not, to stop reading from the connection.

Instead, [this is the code](https://github.com/hyperium/hyper/blob/91e83b7e486da956439df4439b32ad9e9977cbb2/src/proto/h1/decode.rs#L121) that returns an unexpected EOF.

**Comment by Velfi** [comment]
I wrote a test and it's in PR

**Comment by Velfi** [comment]
The PR is merged, pending release.

**Comment by jdisanti** [comment]
Linking the PR: #1906

**Comment by jdisanti** [comment]
There's no equivalent aws-sdk-rust issue for this, so I don't think we need to track release for it.
