### ISSUE TITLE
`changelogger` created an empty changelog entry for `release-2022-10-13`

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1854]
The SDK release on 2022-10-13 went out with an empty changelog for some reason: https://github.com/awslabs/aws-sdk-rust/commit/db33636adc8c171f7669918782e637fabcfbbeaf

- [x] Diagnose and fix root cause of the missing entries
- [ ] ~Add check to fail release on empty changelog~
- [x] Fix author case sensitivity issue (i.e., `LukeMathWalker` is getting converted to `lukemathwalker` before comparison with `smithy-rs-maintainers.txt`)

**Comment by drganjoo** [comment]
So one difference I can think of is that the "Release Smithy-Rs" workflow (a non-dry run) had to be cancelled midway. Maybe this could have caused it?

**Comment by jdisanti** [comment]
The root cause was determined to be that the release workflow was run on a different branch than main, which won't work since it needs to add a changelog update commit. This was addressed by https://github.com/awslabs/smithy-rs/pull/1856

> So one difference I can think of is that the "Release Smithy-Rs" workflow (a non-dry run) had to be cancelled midway. Maybe this could have caused it?

Canceling a release should be fine so long as it hasn't reached the "Push smithy-rs changes" step yet. Otherwise, it is not safe to cancel.

**Comment by jdisanti** [comment]
On second thought, I'm hesitant to add a check to fail on empty changelog since that is a valid use case for aws-sdk-rust right now, if we were to update the models without updating the code generator, since there's currently no mechanism to add model updates to the changelog.
