### ISSUE TITLE
No mechanism for middleware to identify which service/operation a request is for

### ISSUE THREAD

**Issue by jonhoo** [awslabs/smithy-rs#1919]
I'm currently writing a Smithy middleware that allows applying per-operation timeouts. That is, when constructed, the user can supply something like:
```json
{
  "SomeService/this_op": 1000,
  "SomeService/other_op": 86400,
  "SomeService/*": 5000,
  "SomeOtherService/that_op": 50
}
```
and the middleware ensures that the right timeout is applied for each request.

Unfortunately, at the moment, doing so isn't possible (as far as I can tell) because middleware only receive a [`aws_smithy_http::operation::Request`](https://github.com/awslabs/smithy-rs/blob/c5c87be5e684704bf8fdb31e62e5e5c1b37531a8/rust-runtime/aws-smithy-http/src/operation.rs#L258) consisting of a `http::Request<SdkBody>` and a `SharedPropertyBag`, neither of which include the service/operation metadata, which is discarded here:
https://github.com/awslabs/smithy-rs/blob/c5c87be5e684704bf8fdb31e62e5e5c1b37531a8/rust-runtime/aws-smithy-http-tower/src/parse_response.rs#L103-L107

So, my plea: can `Metadata` be included in the `SharedPropertyBag` of a `Request`? Or, alternatively, can the service and operation name be otherwise added to the property bag or `Request` through some other mechanism so that this use-case becomes possible?

**Comment by Velfi** [comment]
This was added a while back but we never closed the ticket until now.
