### ISSUE TITLE
Add S3 customization to prevent accidental data deletion for `AbortMultipartUpload` requests with no ID

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1957]
The `AbortMultiPartUpload` API is ambiguous and will delete an object if no ID is passed, rather than returning an error. Add a customization that will fail the request when no ID is set.

**Comment by rcoh** [comment]
we currently can do this for `{httpLabel}`: https://github.com/awslabs/smithy-rs/blob/b4f294c2770c58148c43411803330c26e369ec14/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/http/RequestBindingGenerator.kt#L246

I'd suggest adding a private trait `Mandatory` or something and then using the same technique to fail the request at serialization time

**Comment by jdisanti** [comment]
The fix for this was included in [release-2022-12-14](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2022-12-14).
