### ISSUE TITLE
Use `mdbook test` on the book

### ISSUE THREAD

**Issue by hlbarber** [awslabs/smithy-rs#2004]
[The book](https://awslabs.github.io/smithy-rs/design/) contains a wealth of examples, all of which can become outdated.

The book is written in markdown, the same format as Rust documentation. If we compile Rust with `#[doc = include_str!(_)]` linking to the book markdown we would be able to run `cargo test` over it to confirm that no Rust is broken. We'd be able to do this in CI to help ensure that we don't break the docs.

An open questions:

- What do we do about [intra-doc links](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html)? Rust documentation and normal GH links provide different ways of linking to items. Using intra-doc links would also allow us to check for dead links to the API in addition to checking for broken examples.
- Do we want to host the `cargo doc` HTML files? Rather than hosting the [mdBook](https://github.com/rust-lang/mdBook) generated files?

**Comment by rcoh** [comment]
yeah the reason we don't run it is it was always a little flaky—maybe it works better now though?

**Comment by hlbarber** [comment]
> yeah the reason we don't run it is it was always a little flaky

Flaky in what way please? I was expecting it to be completely deterministic modulo nondeterminism introduced in the tests.
