### ISSUE TITLE
S3 bucket names are not allowed to contain slashes

### ISSUE THREAD

**Issue by ysaito1001** [awslabs/smithy-rs#2043]
This is an accompanying issue for https://github.com/awslabs/aws-sdk-rust/issues/661.

S3 does not allow bucket names to contain `/` (see [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide//bucketnamingrules.html)) so the reproduction steps in the above issue should return an error, without an HTTP request making its way to the S3 service, saying that such a bucket name is not supported.

This [method](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/BucketUtils.java#L50) in Java SDK V2 checks if a bucket name is valid. In Rust SDK, it can be implemented as a S3 customization. We can add a validation function in `inlineable`, and then pull that in via the customization, which would be a `make_operation` customization.

**Comment by jdisanti** [comment]
@rcoh - Can this validation be done by endpoints 2.0?

**Comment by rcoh** [comment]
yeah

**Comment by rcoh** [comment]
EP2 either supports this or encodes the URI. Either way, we won't support this as custom behavior.
