### ISSUE TITLE
Rename error generators

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#2098]
The error generators currently have the following names:
- TopLevelErrorGenerator - Creates errors for service shapes
- CombinedErrorGenerator - Creates errors for operation shapes
- ErrorGenerator - Creates errors for struct shapes with the `@error` trait

I propose these be renamed to reflect the Smithy shapes they generate errors for:
- ServiceErrorGenerator
- OperationErrorGenerator
- ErrorGenerator

**Comment by crisidev** [comment]
I have always been confused by the original names. I like this proposal!
