### ISSUE TITLE
Investigate the default http connector

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#2151]
Currently the default http connector is `Prebuilt`: https://github.com/awslabs/smithy-rs/blob/bb5bbeb5cff2afb4b3664e95f5c63cae3a524379/aws/rust-runtime/aws-config/src/lib.rs#L463-L466

This means that timeout settings at a service level will be ignored. This should probably be `ConnectorFn` but the implications need to be considered.

**Comment by ysaito1001** [comment]
Fix released in https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-03-30.
