### ISSUE TITLE
A way to construct errors

### ISSUE THREAD

**Issue by jsimpson-gro** [awslabs/smithy-rs#2208]
- https://docs.rs/aws-smithy-http/0.52.0/aws_smithy_http/result/struct.ConstructionFailure.html
    - non-obvious, however if you look in https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/types/enum.SdkError.html there is a constructor of sorts for ConstructionFailure.
- https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/error/struct.Unhandled.html

As I read the docs, it is unclear how I can construct an instance of these struct, which makes unit testing my error handling code unnecessarily difficult.

**Comment by Velfi** [comment]
Could you share a unit test where you'd like to create an error? I'd like to help you and starting with an example makes it easier. You can "create" the error in your example with pseudo-code and then I'll reply with an edited version.

**Comment by jsimpson-gro** [comment]
[testing-s3-connections.tar.gz](https://github.com/awslabs/smithy-rs/files/10490407/testing-s3-connections.tar.gz)

Please don't focus too much on the details. It's just a toy example taken out of context.

**Comment by ysaito1001** [comment]
Fix released in https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-03-30
