### ISSUE TITLE
Explain why "aws-smithy-types" 0.54.2 was yanked

### ISSUE THREAD

**Issue by gyuho** [awslabs/smithy-rs#2361]
Can we update the release note on why this version was yanked?

```
error: failed to select a version for the requirement `aws-smithy-types = "^0.54.2"`
candidate versions found which didn't match: 0.54.1, 0.54.0, 0.53.1, ...
location searched: crates.io index
required by package `avalanche-types v0.0.250`
```

<img width="963" alt="Screenshot 2023-02-14 at 10 25 55 AM" src="https://user-images.githubusercontent.com/6799218/218622956-ac03036f-cfba-438f-aa9b-ca8a1e87e781.png">

**Comment by jdisanti** [comment]
I updated the release notes: https://github.com/awslabs/smithy-rs/releases/tag/release-2023-02-06

There is a 0.54.3 now that resolves the issue that led to the yank.

**Comment by gyuho** [comment]
Thank you!
