### ISSUE TITLE
[Python] Restore PythonServerOperationErrorGenerator extending from ServerOperationErrorGenerator

### ISSUE THREAD

**Issue by pose** [awslabs/smithy-rs#2491]
As part of the #2336 refactor, [`PythonServerOperationErrorGenerator` no longer extends/inherits from `ServerOperationErrorGenerator`](https://github.com/awslabs/smithy-rs/commit/cdc710ddd15b25f53f0c74ceebcea4b60811c31e#diff-2581777d642ae799423a3e345ba3193f02cc51f6e84f618c03683e35c56a20b7):

```diff
class PythonServerOperationErrorGenerator(
    private val model: Model,
    private val symbolProvider: RustSymbolProvider,
    private val operation: OperationShape,
- ) : ServerOperationErrorGenerator(model, symbolProvider, symbolProvider.toSymbol(operation), listOf()) {
- 
+ ) {
    private val operationIndex = OperationIndex.of(model)
    private val errors = operationIndex.getErrors(operation)
```

Each time we change `ServerOperationErrorGenerator` we now need to remember to mirror the same changes on `PythonServerOperationErrorGenerator` which is a rather fragile process and quite likely to be missed.

Unfortunately, we cannot simply extend from `ServerOperationErrorGenerator` as its `render` method is not `open`. How can we make `PythonServerOperationErrorGenerator` extend from `ServerOperationErrorGenerator` on a way we could override the required behavior for the Python and TypeScript cases?

**Comment by crisidev** [comment]
I'll assign this to me as I can bundle this up with a couple of bugfixing I am working on.

**Comment by jdisanti** [comment]
I think we should make `ServerOperationErrorGenerator` configurable like we do with the things in `codegen-core`, and break away from the inheritance to override mentality.

**Comment by crisidev** [comment]
I am of the opposite opinion here. We want to be able to piggy back on as much code as we can from the Rust server implementation for Python and other languages and inheritance seems to me to be filling this gap perfectly.

**Comment by hlbarber** [comment]
One thing to consider here is that we don't always need to extend the Rust generators to TypeScript/Python generators if we're leaving the Rust code intact and just adding code. Instead we can extend the shape visitor so that we visit extra completely separate generators.

Examples: [A](https://github.com/awslabs/smithy-rs/pull/2490/files) and [B](https://github.com/awslabs/smithy-rs/pull/2493/files#diff-a267e56bc35091e6c1f7cf188e93caaf0ff05e927288b9e2b130d9666fd62654)
