### ISSUE TITLE
Can we use the smithy-rs/.../aws-models and generate Swagger definitions (openapi)?

### ISSUE THREAD

**Issue by ikanni** [awslabs/smithy-rs#2549]
It looks like [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models) are used to generate the [aws-sdk-rust/next](https://github.com/awslabs/aws-sdk-rust/tree/next).

How are these files in [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models) are generated?

Can we use the same [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models) and generate Swagger definitions(openapi)? If yes, could you please share the details or steps?

**Comment by rcoh** [comment]
you can use https://smithy.io/2.0/guides/converting-to-openapi.html to convert Smithy models to OpenAPI (but I have not personally tried to do this on those models)
