### ISSUE TITLE
Default request timeouts

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#256]
- [x] Rename API timeouts to operation timeouts and move them into `TimeoutConfig`
- [x] Remove currently unused TCP/HTTP timeout config structs
- [x] Add `connect_timeout` to `TimeoutConfig` and default it to 3100 milliseconds
- [x] Implement support for connect timeout
- [x] Integration test all supported timeouts

**Comment by jdisanti** [comment]
Breaking out the per-operation override capability out into #1732 since that requires a good bit of design work and refactoring.

**Comment by jdisanti** [comment]
Defaults should be the following for now:
```
connectTimeoutInMillis: 3100
tlsNegotiationTimeoutInMillis: 3100
```
Taken from the current `sdk-default-configuration.json` standard mode: https://github.com/awslabs/aws-sdk-rust/blob/a58ba1a21f383b26e09ebdd4cc07d57a87e30388/aws-models/sdk-default-configuration.json#L12-L16

**Comment by jdisanti** [comment]
It looks like only the API timeouts have been implemented, so these defaults can't be set yet. Will need to implement the TCP and HTTP timeouts.
