### ISSUE TITLE
`impl From<f64> for Document`

### ISSUE THREAD

**Issue by andrewbanchich** [awslabs/smithy-rs#2701]
The [`Number`](https://docs.rs/aws-smithy-types/latest/aws_smithy_types/enum.Number.html) type includes a `Float(f64)` variant, but [`Document`](https://docs.rs/aws-smithy-types/latest/aws_smithy_types/enum.Document.html) only implements `From` for signed and unsigned integers.

**Comment by jdisanti** [comment]
Doing this as part of #2708 since I'm in the area.

**Comment by jdisanti** [comment]
This trait has been added and will go out in a future release.
