### ISSUE TITLE
Way to read HTTP Request prior to sending

### ISSUE THREAD

**Issue by nikita-skobov** [awslabs/smithy-rs#2826]
Using [`CustomizableOperation`](https://docs.rs/aws-sdk-s3/0.28.0/aws_sdk_s3/client/customize/struct.CustomizableOperation.html) in theory we can access the HTTP Request, both for reading, or mutation prior to "send"ing the operation.

However a minimal example shows that the request object doesn't actually have the full request that will be sent to the AWS endpoint. 
Here is a minimal example I used:

```rs
async fn helloworld() -> Result<(), Error> {
    let shared_config = aws_config::from_env().load().await;
    let client = Client::new(&shared_config);
    let req = client.head_bucket()
        .bucket("example-bucket")
        .customize().await?;
    println!("{:#?}", req.request());
    let resp = req.send().await?;
    println!("{:#?}", resp);
    Ok(())
}
```

and here is the output of printing the request object:

```
Request {
    method: HEAD,
    uri: /,
    version: HTTP/1.1,
    headers: {},
    body: SdkBody {
        inner: Once(
            Some(
                b"",
            ),
        ),
        retryable: true,
    },
}
```

I believe that is because the actual endpoint, URI, headers, etc. are filled in later by the various Services and Layers here:
https://github.com/awslabs/smithy-rs/blob/d75382789a3d58e6c832d59dd0cc7cce90477a58/rust-runtime/aws-smithy-client/src/lib.rs#L180-L193

Is there a way to read the full request headers, method, URI, and body prior to sending the request?

**Comment by Velfi** [comment]
> Is there a way to read the full request headers, method, URI, and body prior to sending the request?

There will be quite soon. We're going to release an update that changes the internal implementation of the client to easily enable this use case.

Until then, you'd have to write a custom middleware to do this. You'd need to familiarize yourself with the [low-level smithy client builder](https://github.com/awslabs/smithy-rs/blob/ddba46086a9754c01f3b11d7521c49d4489de84b/rust-runtime/aws-smithy-client/src/builder.rs#L149). We don't have guides on this other than the docs in that module.

May I ask what your use case is? Why is it important for you to inspect the request before sending it?

**Comment by nikita-skobov** [comment]
> There will be quite soon. We're going to release an update that changes the internal implementation of the client to easily enable this use case.

Awesome! great news, thank you.

> May I ask what your use case is? Why is it important for you to inspect the request before sending it?

I'd like to use the high level types and convenience builders of the SDK within a wasm environment that does not have access to networking and pass the HTTP request as an object to the host environment such that the host can accept/deny a request prior to sending it. The idea is to allow users to write rust code that gets executed in a wasm environment and declaratively describes the HTTP request that is to be made.

**Comment by Velfi** [comment]
I think with our new implementation of the client (not yet released), we'd want to handle this with a custom connector that would delegate to the "host environment".

The new `Connector` trait is defined thusly:
```rust
use std::fmt;
use std::future::Future as StdFuture;

pub type HttpRequest = http::Request<SdkBody>;
pub type HttpResponse = http::Response<SdkBody>;
pub type BoxError = Box<dyn std::error::Error + Send + Sync>;
pub type BoxFuture<T> = Pin<Box<dyn StdFuture<Output = Result<T, BoxError>> + Send>>;

pub trait Connector: Send + Sync + fmt::Debug {
    fn call(&self, request: HttpRequest) -> BoxFuture<HttpResponse>;
}
```

That way, you can still benefit from retries, timeouts, and more. Think about how you might adapt your "host environment connection" to that interface and keep an eye out for the next version of the SDKs.
