### ISSUE TITLE
Redacting sensitive HTTP responses lost in orchestrator migration

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#2926]
The middleware implementation had a `sensitive()` function on the `ParseHttpResponse` trait that would conditionally redact logging of the HTTP response. This was lost during the orchestrator implementation and needs to be ported over.

Old implementation:
https://github.com/awslabs/smithy-rs/blob/2d61502221d446695f6a0ff9799352ab38ad31cd/rust-runtime/aws-smithy-http/src/response.rs#L64-L69
https://github.com/awslabs/smithy-rs/blob/2d61502221d446695f6a0ff9799352ab38ad31cd/rust-runtime/aws-smithy-http/src/middleware.rs#L137-L145

**Comment by ysaito1001** [comment]
The reason credentials exposure detection tests added in https://github.com/awslabs/smithy-rs/pull/2603 still pass in the orchestrator, even though we haven't ported the pieces of code above to the orcestrator, is that even in the orchestrator, code execution paths still go through [aws_smithy_http::middleware::load_response](https://github.com/awslabs/smithy-rs/blob/2c27834f90b0585dba60606f9da6246b341227d6/rust-runtime/aws-smithy-http/src/middleware.rs#L107). 

As of today, CredentialsProviders in `aws_config`, such as `ImdsCredentialsProvider` and `HttpCredentialProvider`, use a smithy client with middleware ([example](https://github.com/awslabs/smithy-rs/blob/2c27834f90b0585dba60606f9da6246b341227d6/aws/rust-runtime/aws-config/src/http_credential_provider.rs#L48)). This means the pieces of code above are used even in the orchestrator.

Only after middleware has been removed, do credentials exposure detection tests start failing in the orchestrator.
