### ISSUE TITLE
Possibility to set restJson1 protocol http-header prefix

### ISSUE THREAD

**Issue by fredrikbackstrom** [awslabs/smithy-rs#3015]
I've tried searching for similar tasks, and also tried to understand if the better way is not to use AWS jsonRest1 protocols but implement a new one that is not aws specific. 

Context:

I am building a Service with restJson1 as protocol: https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html

Upon a request error the header `"x-amzn-errortype" is automatically added to signal what error type was returned, if possible it would be great if the header prefix used throughout the restJson1 protocol could be configured 

```
@restJson1(
    http: ["h2", "http/1.1"],
    eventStreamHttp: ["h2"]
    xHeaderPrefix: "MyOwnPrefix" 
)
```

https://github.com/awslabs/smithy-rs/blob/f2041a423d92290396fcecbae969d6e4338c4ec4/rust-runtime/aws-smithy-http-server/src/protocol/rest_json_1/runtime_error.rs#L97C22-L97C38

**Comment by jdisanti** [comment]
You should open this feature request in https://github.com/smithy-lang/smithy

Without changes to the spec for the protocol, smithy-rs can't do anything here.
