### ISSUE TITLE
Add a service with a streaming binary input shape

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#347]
The best option on the current roadmap is probably EBS: https://github.com/awslabs/aws-sdk-rust/issues/66

**Comment by richardhboyd** [comment]
such as [Amazon Lex](https://aws.amazon.com/lex/)'s [PostContent API](https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html). Though, it's probably not in really high demand.

**Comment by rcoh** [comment]
Actually lambda has a streaming binary input shape on `invoke`. I'm going to update this ticket to say we should have use that in the example

**Comment by richardhboyd** [comment]
does the new tokio write_all_buf help here or is that just for writing to a file?

**Comment by rcoh** [comment]
That's the opposite direction

**Comment by richardhboyd** [comment]
is the stream writer a functionality in the SDK? I don't think the actual Lambda HTTP API accepts streaming body inputs.

**Comment by rcoh** [comment]
Ah, I looked into it. The stream is actually only on the payload of the deprecated API `invoke_async`

**Comment by rcoh** [comment]
done from s3
