### ISSUE TITLE
Update example code to use `write_all_buf`

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#349]
`write_all_buf` was added to `AsyncWriteExt` which is a one-liner for writing a buf to a file directly. Suggest people use this in example code in `ByteStream` as well as in examples like Polly synthesize speech.

**note:** requires new Tokio release containing https://github.com/tokio-rs/tokio/pull/3737

**Comment by rcoh** [comment]
Tokio 1.6.0 has landed with the new API 🎉

**Comment by LMJW** [comment]
Hi @rcoh. Just created a small PR for updating the examples. Please let me know if you have any feedbacks. Thanks :)

**Comment by rcoh** [comment]
Thanks @LMJW!
