### ISSUE TITLE
Have one example package per service rather than one per operation

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#400]
Currently, we have two classes of examples for each service (operation and "hello world"), and each one of these has its own Cargo package, which means with just 8 services, we have 28 example packages with their own Cargo.toml file. It seems like this may not scale in the long run, especially in regards to updating dependencies across the examples.

We should refactor the examples so that there is one example Cargo package per service. So rather than:
- dynamo-add-item
- dynamo-create-table
- dynamo-delete-item

We should have just "dynamo", and inside of that, we have different operation and "hello world" examples as separate module files:
- dynamo
  - add-item.rs
  - create-table.rs
  - delete-item.rs
  - etc...

**Comment by Doug-AWS** [comment]
Good point. I'll make the changes soon.

**Comment by rcoh** [comment]
Dynamodb is now also done
