### ISSUE TITLE
Enforce member uniqueness for set shapes

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#44]
Probably something like:
```rust
struct Set<T: Hash>(Vec<T>)
```

**Comment by david-perez** [comment]
Smithy spec says sets have to be backed by an insertion-ordered container; there are none in stdlib. We should wrap some crate like [`linked_hash_set`](https://crates.io/crates/linked_hash_set) and expose the type from `aws_smithy_types`.

I don't think this is a priority for smithy-rs clients, but we will eventually have to do this for servers.

**Comment by david-perez** [comment]
Closing this due to https://github.com/awslabs/smithy/pull/1278.
