### ISSUE TITLE
Instance metadata credentials support

### ISSUE THREAD

**Issue by twitu** [awslabs/smithy-rs#466]
`aws-auth` currently does not support retrieving credentials from instance metadata service. This has also been brought up as an [issue](https://github.com/awslabs/aws-sdk-rust/issues/97) in aws-sdk-rust repo.

**Comment by twitu** [comment]
As mentioned in comments [this](https://github.com/awslabs/aws-sdk-rust/issues/97#issuecomment-855650582) and [this](https://github.com/awslabs/aws-sdk-rust/issues/97#issuecomment-855650582). This can be solved in two ways

1. Creating a credentials provider that takes input role and default region and queries the instance metadata url to retrieve the credentials
2. Creating a credentials provider that reads the configuration file or environment variables and checks if `credential_source = Ec2InstanceMetadata` is set. If this is set it queries the instance metadata for credentials.

Any thoughts around this will be helpful.

**Comment by twitu** [comment]
This also points to a larger issue with the current implementation that it does not read the `~/.aws/config` file and there's no way to choose which profile it will use.

**Comment by rcoh** [comment]
shipped in #709
