### ISSUE TITLE
DateTime/HttpDate formatting shouldn't panic for out of range instants

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#494]
We need to refactor date formatting and code generation around it so that it's fallible.

HttpDate panic: https://github.com/awslabs/smithy-rs/blob/dbe0dc0eca4837f96f0dfc08acd165edc6210a27/rust-runtime/smithy-types/src/instant/format.rs#L98

DateTime panic: https://github.com/awslabs/smithy-rs/blob/dbe0dc0eca4837f96f0dfc08acd165edc6210a27/rust-runtime/smithy-types/src/instant/format.rs#L456-L459

**Comment by rcoh** [comment]
@jdisanti is this fixed?

**Comment by jdisanti** [comment]
Yes. This was done in https://github.com/awslabs/smithy-rs/pull/849, specifically in commit https://github.com/awslabs/smithy-rs/pull/849/commits/fb692d0c0c0bff2ae087a965d1780460a5777691. Closing.
