### ISSUE TITLE
generic API for modifying headers

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#605]
see #583 

There should be a generic way to add headers to request

**Comment by rcoh** [comment]
key-val support for adding to the user agent

**Comment by marcbowes** [comment]
We (qldb) are just about ready to ship our 2.0 shell based on the awssdk for Rust. At this point, setting the user agent is the only blocking issue in terms of feature parity. If you give us some pointers, we can probably contribute this.

**Comment by rcoh** [comment]
Because you’re already using the low level API, you can actually do this directly with no code changes on the SDK side, just use `properties_mut()` on the operation to set a custom `AwsUserAgent`

**Comment by rcoh** [comment]
we may need some very small changes depending on exactly what you want the user agent to be, but those should be quite minor and isolated

**Comment by rcoh** [comment]
A workable pattern for this:
https://gist.github.com/rcoh/14668328600aa8989b679e42ee92d45f

**Comment by jdisanti** [comment]
[RFC for this feature](https://github.com/awslabs/smithy-rs/blob/main/design/src/rfcs/rfc0017_customizable_client_operations.md)

**Comment by jdisanti** [comment]
Resolving this in favor of #1112. Looks like it got duplicated.
