### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by MikailBag** [awslabs/smithy-rs#665]
Hello. Is there any instruction on how to use smithy-rs or some example? All documentations I saw only describes how to generate AWS SDK.

In general it seems that I need to run `./gradlew publishToMavenLocal` in `smithy-rs` root and then write correct `build.gradle.kts` & `smithy-build.json`, but so far I `gradle build` fails with an error `Could not find software.amazon.rustruntime:rust-runtime:0.0.3.` and I have no idea how to fix it.

**Comment by rcoh** [comment]
can you give a little more info on what you're trying to do? Are you trying to generate an SDK for a custom model? In general, this repo is used by running `./gradlew <sometask>`.

Some examples: https://github.com/awslabs/smithy-rs/tree/main/aws/sdk

**Comment by MikailBag** [comment]
>  what you're trying to do
I have a `.smithy` file describing my hobby project API and I'd like to generate a client for this API.

>  Are you trying to generate an SDK for a custom model
Yes. And I don't see how it is done.

It is definitely possible (because AWS SDK is generated somehow), but the setup in `./aws` seems to be pretty complicated.

**Comment by jdisanti** [comment]
We only have two examples right now: the AWS SDK, and the `codegen-test` sub-package. Like you say, they're pretty complicated, and weren't really intended as examples.

I think setting this up boils down to a three step process:
1. Compile smithy-rs and get the resultant jar file
2. In your project, create a smithy-build.json file to describe the codegen settings. You can see examples of these in the build artifacts, but here's a minimal example:
```
{
   "version": "1.0",
   "plugins": {
      "rust-codegen": {
         "runtimeConfig": {
           "relativePath": "../"
         },
         "codegen": {
            "includeFluentClient": false,
            "renameErrors": false
         },
         "service": "namespace.to#MyServiceShape",
         "module": "my-service",
         "moduleVersion": "0.1",
         "moduleAuthors": ["example <example@example.com>"],
         "license": "ISC"
      }
   }
}
```
I think the `runtimeConfig.relativePath` on that needs to point to the `rust-runtime` directory in smithy-rs.
3. Put that compiled jar on a classpath with the Smithy CLI jar, and then run a Smithy build with the plugin listed. For example:
```
$ java -cp path/to/smithyrs.jar:path/to/smithy.jar software.amazon.smithy.cli.SmithyCli build --plugin rust-codegen
```
If I got that correct, then that will generate a client that doesn't do any kind of authentication. To add auth, you will need to customize the middleware.

**Comment by MikailBag** [comment]
Thanks for your hints!

So it seems that following jars are needed (at least I stopped getting ClassDefNotFound exceptions after adding all of these to `java -cp`):
- `smithy/smithy-cli/build/libs/smithy-cli-${SMITHY_VERSION}.jar`
- `smithy/smithy-model/build/libs/smithy-model-${SMITHY_VERSION}.jar`
- `smithy/smithy-utils/build/libs/smithy-utils-${SMITHY_VERSION}.jar`
- `smithy/smithy-build/build/libs/smithy-build-${SMITHY_VERSION}.jar`
- `smithy/smithy-aws-traits/build/libs/smithy-aws-traits-${SMITHY_VERSION}.jar`

Also, I had to pass `--discover` flag to the `smithy-cli` invocation.

After these, smithy-cli correctly starts up, parses the model, loads rust-codegen.

However I see a following error then:
```
Projection user-login failed: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
software.amazon.smithy.rust.codegen.smithy.RustCodegenPlugin.execute(RustCodegenPlugin.kt)
software.amazon.smithy.build.SmithyBuildImpl.applyPlugin(SmithyBuildImpl.java:376)
software.amazon.smithy.build.SmithyBuildImpl.applyProjection(SmithyBuildImpl.java:313)
software.amazon.smithy.build.SmithyBuildImpl.executeSerialProjection(SmithyBuildImpl.java:223)
software.amazon.smithy.build.SmithyBuildImpl.lambda$applyAllProjections$5(SmithyBuildImpl.java:188)
java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1453)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
So it seems that smithy-rs jar depends on some other jars (most likely kotlin standard library) which are not installed on my system.
Is it possible to build a self-contained jar? I currently use `./gradlew assemble` command.

**Comment by jdisanti** [comment]
You need to pull in all of the jars that are dependencies of smithy-rs to get it up and running. Something you could try is [adding a shadow jar task](https://github.com/johnrengelman/shadow) to `sdk-codegen`'s gradle build. This will build a jar file with all of the dependencies bundled. I think you will still need the `smithy-cli` and `smithy-aws-traits` jar files on the classpath after that though.

**Comment by MikailBag** [comment]
Thanks for this pointer!

I can confirm that [this](https://github.com/MikailBag/smithy-docker/blob/0b8c04bd469992e38ad603ccd642b759c807c0c8/Dockerfile) Dockerfile works (i.e. produces some Rust files).
