### ISSUE TITLE
Remove S3 model hack and use customization instead for `Size`

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#680]
https://github.com/awslabs/smithy-rs/pull/679 added a hack to `sync-models.py` to correct S3's `Size` to be a long instead of an int since it wasn't possible to do it with Smithy's `ModelTransformer` at the time.

This issue tracks removing this hack and enabling `S3CorrectSizeIntegerType` customization once https://github.com/awslabs/smithy/pull/900 lands.

Touch points:
- https://github.com/awslabs/smithy-rs/blob/8676d8dcf79ac187a77dbd9b2b355b00ee0171fd/aws/sdk/sync-models.py#L49-L50
- https://github.com/awslabs/smithy-rs/blob/8676d8dcf79ac187a77dbd9b2b355b00ee0171fd/aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3Decorator.kt#L62-L65
- https://github.com/awslabs/smithy-rs/blob/8676d8dcf79ac187a77dbd9b2b355b00ee0171fd/aws/sdk-codegen/src/test/kotlin/software/amazon/smithy/rustsdk/customize/s3/S3DecoratorTest.kt#L18-L20

**Comment by rcoh** [comment]
fixed a while ago
