### ISSUE TITLE
Fix aws-sigv4 canonical request formatting fallibility

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#711]
The aws-sigv4 crate currently implements the `Display` trait for formatting the canonical request, and since it's using `ToString` to do the actual formatting, it will panic if there's any error during that formatting.

In #710, we fixed a bug where header values that contained non-ASCII characters would cause a panic, but the problem was just punted a little bit since now it can panic if there's invalid UTF-8 in the header value.

Options we should evaluate and choose from:
1. Refactor `CanonicalRequest` to have a fallible format function instead of implementing `Display`, and bubble the error up.
2. Refactor `CanonicalRequest` to have an infallible format function, but produce bytes instead of a string, and put the header value's bytes directly into the formatted canonical request.

**Comment by Velfi** [comment]
Russell wrote a (currently failing) test case for this issue:

```rust
#[test]
    fn test_signing_utf8_headers() {
        let req = http::Request::builder()
            .uri("https://foo.com/")
            .header("x-sign-me", HeaderValue::from_bytes(&[0xC0, 0xC1]).unwrap())
            .body(&[])
            .unwrap();
        let creq = crate::http_request::sign(
            SignableRequest::from(&req),
            &SigningParams::builder()
                .region("us-east-1")
                .access_key("123")
                .service_name("foo")
                .secret_key("asdf")
                .time(SystemTime::now())
                .settings(SigningSettings::default())
                .build()
                .unwrap(),
        );
    }
```
