### ISSUE TITLE
CI Action to check licenses of dependencies

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#764]
We should have a CI action that checks that:
- [x] the license in our runtime crates is correct, that 
- [x] the `LICENSE` file exists, and also that 
- [x] all of their dependencies have compatible licenses.

**Comment by mlycore** [comment]
How about using FOSSA for dependencies licenses check ?

**Comment by jdisanti** [comment]
> How about using FOSSA for dependencies licenses check ?

I think we can get away with something as simple as running `cargo-deny` with a list of allowed licenses. Thanks for the suggestion though!
