### ISSUE TITLE
generate field accessors instead of public fields on inputs/outputs

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#829]
Field accessors are created, however, public fields have not yet been removed. There are a few issues that need to be addressed:
- [x] #117 (because it's hard to paginate manually without public fields)
- [ ] #943 
- [ ] DynamoDB `item` on `GetItemOutput` and `ScanOutput` (for example), would benefit from direct access for compatibility with `serde_dynamo`

**Comment by jdisanti** [comment]
I think we should reevaluate if accessors are the right approach. They seem to complicate streaming bodies and DynamoDB use cases.

**Comment by crisidev** [comment]
I am not sure if this is what we want for the server. If you go with this solution, let's discuss first if we want to have it as part of `core` or just `client`.

**Comment by jdisanti** [comment]
Closing this in favor of #2325
