### ISSUE TITLE
Unnecessary use of Option<T> on required fields

### ISSUE THREAD

**Issue by allan2** [awslabs/smithy-rs#837]
An example is `HostedZone`, which has required fields that are wrapped in `Option`.
```rust
#[non_exhaustive]
pub struct HostedZone {
    pub id: Option<String>,                      // required
    pub name: Option<String>,                    // required
    pub caller_reference: Option<String>,        // required
    pub config: Option<HostedZoneConfig>,
    pub resource_record_set_count: Option<i64>,  // probably is always Some(i64)
    pub linked_service: Option<LinkedService>,
}
```
The [Go API Reference](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#HostedZone) states that those fields are required.

The JS API also has a similar typing problem when generating from Smithy . Their `HostedZone` has the type `string | undefined` for `id`. There is an open issue: [Why is everything possibly undefined? (& other typing/doc questions)](https://github.com/aws/aws-sdk-js-v3/issues/1613) 

Is there an authoritative source on whether fields are required for the AWS SDK? 
It would be nice to have direct access to fields if they are always `Some<T>` 🙂

References
[[1]](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#HostedZone) HostedZone, Go API Reference
[[2]](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/modules/hostedzone.html) HostedZone, JavaScript v3 API Reference

**Comment by jdisanti** [comment]
Take a look at https://github.com/awslabs/aws-sdk-rust/discussions/163 and feel free to join in on the conversation there.

I think the best way to tell if a field is required right now is to look at the service's API docs, which typically state the requiredness of each field. For example, for CreateHostedZone, the fields have a `Required: Yes`:
https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html

This isn't ideal though, and we're working on improving it.

**Comment by llgerard** [comment]
Linked issue: #1095

**Comment by david-perez** [comment]
@llgerard Just want to note that #1095 is unrelated to this issue, since #1095 is for the _server_ implementation, while this one is for the _client_. The client does not have as much freedom as the server, since it needs to be able to work with older versions of the Smithy model, and the spec says that [removing the `required` trait is a backwards-compatible change](https://awslabs.github.io/smithy/1.0/guides/evolving-models.html?highlight=backwards#updating-structures).

**Comment by Velfi** [comment]
I'm going to close this in favor of aws-sdk-rust#536, which covers the same subject.

**Comment by jdisanti** [comment]
It's being tracked in https://github.com/awslabs/smithy-rs/issues/1767 on the smithy-rs side.
