### ISSUE TITLE
Remove dependency on `derive_builder` from `aws-smithy-http-server`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy-rs#864]
In #850, I introduced a dependency on [`derive_builder`](lib.rs/derive_builder), which depends on `syn`, which is a large crate.

[As pointed out](https://github.com/awslabs/smithy-rs/pull/850#discussion_r750475861), we should create our own builders in the Kotlin code-generator.

**Comment by crisidev** [comment]
Resolved by #894
