### ISSUE TITLE
Automatically sync `aws-sdk-rust`'s `next` branch whenever a commit is made to `smithy-rs`'s `main` branch

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#928]
Commits to main of smithy-rs would push to the `next` branch of aws-sdk-rust. As part of cutting the release, we would:
- automatically or manually run update manifests
- bump version numbers
- update changelogs
This has a number of advantages:
- easy to see changes caused by individual commits in the generated code
- generated code will have actual commit history
- it's possible to depend on unreleased code by specifying the branch or tag

**Comment by jdisanti** [comment]
This was finished a long time ago.
