### ISSUE TITLE
[Server] Implement httpQuery and httpQueryParams traits for input types

### ISSUE THREAD

**Issue by crisidev** [awslabs/smithy-rs#937]
Implement deserializers for [httpQuery](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpquery-trait) and [httpQueryParams](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpqueryparams-trait).

We could probably generate [nom](https://docs.rs/nom/latest/nom/) parsers on the fly.

**Comment by david-perez** [comment]
No nom parsers needed, splitting and percent-decoding the query string suffices.

Note however that we're not fully compliant with the Smithy spec, see https://github.com/awslabs/smithy-rs/issues/972.
