### ISSUE TITLE
Refactor LazyCachingCredentialsProvider creation to make it less error-prone

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#952]
The smithy-rs#949 fix demonstrates that it's easy to mix up the order of arguments when creating a `LazyCachingCredentialsProvider`. Refactor the method of creating a `LazyCachingCredentialsProvider` so that it's difficult to make a mistake when constructing one, perhaps by implementing a builder or by making the struct fields `pub`

**Comment by jdisanti** [comment]
The constructor on this is private, so I don't think this needs to happen.
