### ISSUE TITLE
Don't use booleans as function argument for function with 2+ arguments

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#964]
Instead, we should use enums with descriptive names:

```rust
const GREEDY: &AsciiSet = &LABEL_SET.remove(b'/');

pub enum EncodingStrategy {
  Default,
  Greedy,
}

pub fn fmt_string<T: AsRef<str>>(t: T, strategy: EncodingStrategy) -> String {
    let uri_set = if strategy == Greedy { GREEDY } else { LABEL_SET };
    percent_encoding::utf8_percent_encode(t.as_ref(), uri_set).to_string()
}

let _ = fmt_string("some str", EncodingStrategy::Greedy);
// used to look like
// let _ = fmt_string("some str", true);
```

**Comment by jdisanti** [comment]
Code referenced: https://github.com/awslabs/smithy-rs/blob/a0539e20b069a7de021c84521d8f3c7ba098ad6d/rust-runtime/aws-smithy-http/src/label.rs#L16

**Comment by ysaito1001** [comment]
I am a fan of replacing bools with enums in function parameters. As part of this breaking change, do we want to make `urlencode::BASE_SET: &AsciiSet` `pub(crate)` (I think it's referred to as `LABEL_SET` in the given code snippet above)? As far as I can see, that's the only item for which we expose `AsciiSet` from this crate, and if we can avoid exposing it, would that be better?

**Comment by jdisanti** [comment]
`AsciiSet` comes from the `percent_encoding` crate, so it would be best to not expose it in the public API. That way, if `percent_encoding` makes breaking changes in a new major version, we will be able to upgrade to that version without making breaking changes.
