### ISSUE TITLE
fluent builders generate useless `Into<impl T>`

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#990]
eg: https://docs.rs/aws-sdk-dynamodb/0.3.0/src/aws_sdk_dynamodb/client.rs.html#1671-1677

**Comment by jasonmccampbell** [comment]
Hi, prior to this change, I had implement the From trait converting from my internal types to AttributeValue. This allowed the types to be passed in easily and the appropriate conversion is handled under the overs. ex: .item(COL_PASSWORD, hashed_pw)

I can update the code to explicitly call .into() for every call. Is this the expected pattern? Or is there another preferred pattern? Why is the Into<Impl t> decorations are considered useless?
